"""make exception start and end times required to match recurring availability

Revision ID: 343ee157bf53
Revises: 9785a72744e1
Create Date: 2026-07-30 12:28:30.193463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '343ee157bf53'
down_revision: Union[str, Sequence[str], None] = '9785a72744e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('availability_exceptions', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('availability_exceptions', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('availability_exceptions', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('availability_exceptions', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    # ### end Alembic commands ###
