"""initial schema

Revision ID: 9785a72744e1
Revises: 
Create Date: 2026-07-16 21:39:55.464419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9785a72744e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('availability_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_profiles_id'), 'availability_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_availability_profiles_user_id'), 'availability_profiles', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('range_start', sa.Date(), nullable=True),
    sa.Column('range_end', sa.Date(), nullable=True),
    sa.Column('invite_code', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('range_start IS NULL OR range_end IS NULL OR range_end >= range_start', name='ck_event_date_order'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_created_by'), 'events', ['created_by'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_invite_code'), 'events', ['invite_code'], unique=True)
    op.create_table('availability_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('exception_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('free', 'if_needed', 'busy')", name='ck_exception_status'),
    sa.CheckConstraint('(start_time IS NULL AND end_time IS NULL) OR (start_time IS NOT NULL AND end_time IS NOT NULL AND end_time > start_time)', name='ck_exception_time_shape'),
    sa.ForeignKeyConstraint(['profile_id'], ['availability_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_exceptions_exception_date'), 'availability_exceptions', ['exception_date'], unique=False)
    op.create_index(op.f('ix_availability_exceptions_id'), 'availability_exceptions', ['id'], unique=False)
    op.create_index(op.f('ix_availability_exceptions_profile_id'), 'availability_exceptions', ['profile_id'], unique=False)
    op.create_table('event_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('guest_name', sa.String(length=100), nullable=True),
    sa.Column('guest_password_hash', sa.String(length=255), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(user_id IS NOT NULL AND guest_name IS NULL) OR (user_id IS NULL AND guest_name IS NOT NULL)', name='ck_participant_user_or_guest'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['availability_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_user')
    )
    op.create_index('idx_unique_guest_name_per_event', 'event_participants', ['event_id', sa.literal_column('lower(guest_name)')], unique=True, postgresql_where=sa.text('guest_name IS NOT NULL'))
    op.create_index(op.f('ix_event_participants_event_id'), 'event_participants', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_participants_id'), 'event_participants', ['id'], unique=False)
    op.create_table('recurring_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('free', 'if_needed', 'busy')", name='ck_recurring_status'),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name='ck_recurring_day_of_week'),
    sa.CheckConstraint('end_time > start_time', name='ck_recurring_time_order'),
    sa.ForeignKeyConstraint(['profile_id'], ['availability_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_availability_id'), 'recurring_availability', ['id'], unique=False)
    op.create_index(op.f('ix_recurring_availability_profile_id'), 'recurring_availability', ['profile_id'], unique=False)
    op.create_table('event_participant_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('free', 'if_needed', 'busy')", name='ck_participant_avail_status'),
    sa.CheckConstraint('end_time > start_time', name='ck_participant_avail_time_order'),
    sa.ForeignKeyConstraint(['participant_id'], ['event_participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_participant_availability_date'), 'event_participant_availability', ['date'], unique=False)
    op.create_index(op.f('ix_event_participant_availability_id'), 'event_participant_availability', ['id'], unique=False)
    op.create_index(op.f('ix_event_participant_availability_participant_id'), 'event_participant_availability', ['participant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_participant_availability_participant_id'), table_name='event_participant_availability')
    op.drop_index(op.f('ix_event_participant_availability_id'), table_name='event_participant_availability')
    op.drop_index(op.f('ix_event_participant_availability_date'), table_name='event_participant_availability')
    op.drop_table('event_participant_availability')
    op.drop_index(op.f('ix_recurring_availability_profile_id'), table_name='recurring_availability')
    op.drop_index(op.f('ix_recurring_availability_id'), table_name='recurring_availability')
    op.drop_table('recurring_availability')
    op.drop_index(op.f('ix_event_participants_id'), table_name='event_participants')
    op.drop_index(op.f('ix_event_participants_event_id'), table_name='event_participants')
    op.drop_index('idx_unique_guest_name_per_event', table_name='event_participants', postgresql_where=sa.text('guest_name IS NOT NULL'))
    op.drop_table('event_participants')
    op.drop_index(op.f('ix_availability_exceptions_profile_id'), table_name='availability_exceptions')
    op.drop_index(op.f('ix_availability_exceptions_id'), table_name='availability_exceptions')
    op.drop_index(op.f('ix_availability_exceptions_exception_date'), table_name='availability_exceptions')
    op.drop_table('availability_exceptions')
    op.drop_index(op.f('ix_events_invite_code'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_created_by'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_availability_profiles_user_id'), table_name='availability_profiles')
    op.drop_index(op.f('ix_availability_profiles_id'), table_name='availability_profiles')
    op.drop_table('availability_profiles')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
