"""accommodate time constraints per event

Revision ID: dbb343abc4d4
Revises: 343ee157bf53
Create Date: 2026-08-01 00:46:17.282744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbb343abc4d4'
down_revision: Union[str, Sequence[str], None] = '343ee157bf53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('window_start_time', sa.Time(), nullable=True))
    op.add_column('events', sa.Column('window_end_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'window_end_time')
    op.drop_column('events', 'window_start_time')
    # ### end Alembic commands ###
